---
- name: Node Executor Playbook
  hosts: "{{ host }}"
  become: yes
  vars:
    svc: "{{ service_name }}"
    version: "{{ deploy_version }}"
    package_url: "{{ package_url }}"
    package_sha256: "{{ package_sha256 }}"
    release_dir: "/opt/releases/{{ svc }}/{{ version }}"
    systemd_unit: "/etc/systemd/system/{{ svc }}@{{ version }}.service"
    prev_version: "{{ prev_version }}"
  tasks:

    - name: Ensure release directory exists
      file:
        path: "{{ release_dir }}"
        state: directory
        mode: '0755'

    - name: Download package
      get_url:
        url: "{{ package_url }}"
        dest: "{{ release_dir }}/{{ svc }}.tar.gz"
        mode: '0644'

    - name: Verify SHA256 checksum
      shell: "sha256sum {{ release_dir }}/{{ svc }}.tar.gz | awk '{print $1}'"
      register: sha256sum_out
      changed_when: false

    - name: Fail if checksum mismatch
      fail:
        msg: "SHA256 checksum mismatch for {{ svc }} version {{ version }}"
      when: sha256sum_out.stdout != package_sha256

    - name: Extract package
      unarchive:
        src: "{{ release_dir }}/{{ svc }}.tar.gz"
        dest: "{{ release_dir }}"
        remote_src: yes
        extra_opts:
          - --strip-components=1

    - name: Render systemd unit
      template:
        src: "templates/{{ svc }}@.service.j2"
        dest: "{{ systemd_unit }}"
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
    - name: Stop previous version if exists
      systemd:
        name: "{{ svc }}@{{ prev_version }}"
        state: stopped
      when: prev_version is defined and prev_version | length > 0
      ignore_errors: yes
    - name: Restart service
      systemd:
        name: "{{ svc }}@{{ version }}"
        state: restarted
        enabled: yes

    - name: Rollback service to previous version
      systemd:
        name: "{{ svc }}@{{ prev_version }}"
        state: started
      when: rollback | default(false)
